spring:
    application:
        name: bitbucket-watcher

teams:
    url: https://og2gether.webhook.office.com/webhookb2/2307fa4a-e405-4e5b-a688-ceb95e5c095e@8794e153-c3bd-4479-8bea-61aeaf167d5a/IncomingWebhook/013ff38771e34faf94c8c540cb9e6bbb/3ec030f9-4c49-484d-b8a5-5cc8ff85634a
    readTimeout: 60
    connectTimeout: 60

bitbucket:
    base-url: https://bitbucket.otto.de/
    readTimeout: 60
    connectTimeout: 60
    project-key: sp
    repo-slug: salesproduct
    username: clschuet
    password: z4mr3BF?#A
    pull-request:
        cron: 0 0/1 * ? * *
    branch:
        cron-check: 0 0/10 * ? * *
        cron-clear: 0 0 7 ? * *

server:
    port: 8080
management:
    endpoint:
        health:
            show-details: always
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: info, health, metrics, prometheus
